# Generated by Django 4.0.4 on 2022-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('seq', models.CharField(max_length=80)),
                ('complete', models.BooleanField()),
            ],
            options={
                'db_table': 'task',
                'ordering': ['seq'],
            },
        ),
    ]
